spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:C:\Users\JJ\Downloads\todo-full\MoneyAppV5\money-db'
#    url: 'jdbc:h2:file:D:\inteliJProjects\MoneyAppV5\money-db'
    java:
  jpa:
    hibernate:
      ddl-auto: validate
management:
  endpoints:
    web:
      exposure:
        include: '*'
#keycloak:
#  auth-server-url: 'http://localhost:8180/auth'
#  realm: 'MoneyAppV4'
#  resource: 'money-spring-client'
#  public-client: true